### ISSUE TITLE
Example for HSM

### ISSUE THREAD

**Issue by binarymaker** [kiishor/UML-State-Machine-in-C#27]
Please provide sample example for advanced hierarchical state machine. its little difficult to understand without demo usage code. example model like this
![68747470733a2f2f696d6775722e636f6d2f47445a416542392e706e67](https://user-images.githubusercontent.com/45413608/73533003-da0cf000-4443-11ea-93ab-929e6fbfae98.png)

**Comment by kiishor** [comment]
Thanks for your suggestion. I will add it soon..

**Comment by kiishor** [comment]
@binarymaker I have added one more example for a hierarchical state machine. Let me know you need any additional example or enhancement.
